-- AlterTable
ALTER TABLE `audit_logs` MODIFY `action` ENUM('LOGIN', 'LOGIN_FAILED', 'LOGOUT', 'PASSWORD_RESET_REQUESTED', 'PASSWORD_RESET_COMPLETED', 'ROLE_CHANGED', 'ORG_SERVICE_GRANTED', 'ORG_SERVICE_REVOKED', 'DASHBOARD_ACCESSED', 'USER_CREATED_BY_ADMIN', 'ACTIVATION_INVITE_RESENT', 'ACCOUNT_ACTIVATED', 'USER_SUSPENDED', 'USER_REACTIVATED', 'PROFILE_UPDATED', 'VARIABLES_UPLOADED', 'ORGANIZATION_UPDATED', 'SERVICE_CREATED', 'SERVICE_UPDATED', 'VARIABLE_READING_CORRECTED') NOT NULL;

-- AlterTable
ALTER TABLE `variable_readings` ADD COLUMN `corrected_at` DATETIME(3) NULL,
    ADD COLUMN `corrected_by_id` VARCHAR(191) NULL,
    ADD COLUMN `correction_reason` TEXT NULL,
    ADD COLUMN `is_corrected` BOOLEAN NOT NULL DEFAULT false;

-- AddForeignKey
ALTER TABLE `variable_readings` ADD CONSTRAINT `variable_readings_corrected_by_id_fkey` FOREIGN KEY (`corrected_by_id`) REFERENCES `users`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;

