-- AlterTable
ALTER TABLE `notifications` MODIFY `type` ENUM('SEMAFORO_CRITICO', 'CARGA_PROCESADA', 'CARGA_CON_ERROR', 'CUENTA_SUSPENDIDA', 'CUENTA_REACTIVADA', 'REGISTRO_PENDIENTE', 'CONTACTO_RECIBIDO', 'LECTURA_CORREGIDA') NOT NULL;

-- AlterTable
ALTER TABLE `variable_uploads` ADD COLUMN `omitted_rows` JSON NULL;

