-- AlterTable
ALTER TABLE `audit_logs` MODIFY `action` ENUM('LOGIN', 'LOGIN_FAILED', 'LOGOUT', 'PASSWORD_RESET_REQUESTED', 'PASSWORD_RESET_COMPLETED', 'ROLE_CHANGED', 'ORG_SERVICE_GRANTED', 'ORG_SERVICE_REVOKED', 'DASHBOARD_ACCESSED', 'USER_CREATED_BY_ADMIN', 'ACTIVATION_INVITE_RESENT', 'ACCOUNT_ACTIVATED', 'USER_SUSPENDED', 'USER_REACTIVATED', 'PROFILE_UPDATED', 'VARIABLES_UPLOADED', 'ORGANIZATION_UPDATED', 'SERVICE_CREATED', 'SERVICE_UPDATED', 'VARIABLE_READING_CORRECTED', 'ORGANIZATION_BRANDING_SET', 'VARIABLE_DEFINITION_UPDATED') NOT NULL;

-- AlterTable
ALTER TABLE `variable_definitions` ADD COLUMN `incertidumbre` VARCHAR(100) NULL,
    ADD COLUMN `instrumento` VARCHAR(255) NULL,
    ADD COLUMN `tipo` ENUM('MEDICION', 'CALCULO', 'INSPECCION') NULL;

